models:
 - name: fact_sales
   columns:
   - name: order_item_id
     tests: [unique, not_null]
   - name: customer_id
     tests: [{relationships: {to: ref('dim_customer'), field: customer_id}}]
   - name: product_id
     tests: [{relationships: {to: ref('dim_product'), field: product_id}}]